include: package:flutter_lints/flutter.yaml
# This is a set of rules for this project.
# Please prefer to: https://dart.dev/tools/linter-rules

linter:
  rules:
    avoid_function_literals_in_foreach_calls: false
    prefer_single_quotes: true
    empty_statements: true
    no_duplicate_case_values: true
    prefer_relative_imports: true
    unnecessary_statements: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: false
    always_put_required_named_parameters_first: true
    annotate_overrides: true
    avoid_classes_with_only_static_members: false
    prefer_const_constructors: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    camel_case_extensions: true
    camel_case_types: true
    directives_ordering: true
    empty_catches: true
    file_names: true
    leading_newlines_in_multiline_strings: true
    prefer_final_locals: false
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    unnecessary_brace_in_string_interps: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true